export const browserCoreExamples = [
  "sudoclaw browser status",
  "sudoclaw browser start",
  "sudoclaw browser stop",
  "sudoclaw browser tabs",
  "sudoclaw browser open https://example.com",
  "sudoclaw browser focus abcd1234",
  "sudoclaw browser close abcd1234",
  "sudoclaw browser screenshot",
  "sudoclaw browser screenshot --full-page",
  "sudoclaw browser screenshot --ref 12",
  "sudoclaw browser snapshot",
  "sudoclaw browser snapshot --format aria --limit 200",
  "sudoclaw browser snapshot --efficient",
  "sudoclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "sudoclaw browser navigate https://example.com",
  "sudoclaw browser resize 1280 720",
  "sudoclaw browser click 12 --double",
  'sudoclaw browser type 23 "hello" --submit',
  "sudoclaw browser press Enter",
  "sudoclaw browser hover 44",
  "sudoclaw browser drag 10 11",
  "sudoclaw browser select 9 OptionA OptionB",
  "sudoclaw browser upload /tmp/sudoclaw/uploads/file.pdf",
  'sudoclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "sudoclaw browser dialog --accept",
  'sudoclaw browser wait --text "Done"',
  "sudoclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "sudoclaw browser console --level error",
  "sudoclaw browser pdf",
];
